### ISSUE TITLE
Comments for `Raspberry Pi Time-Lapse Camera Pt 1`

### ISSUE THREAD

**Issue by schwartzworld** [ianschwartz/site#12]

**Comment by mikedinicola** [comment]
2 issues *URGENT*

1. You linked here from both part 1 and part 2
2. Part 2 video is as corrupt as Joe Biden

**Comment by schwartzworld** [comment]
Yes thank you thank you. I'm actually aware of both problems but haven't written any code all week due to Thanksgiving / school closure. 

I actually need to tweak the video format anyway because apparently mp4 isn't supported by Firefox. Maybe webm? Is that legit for safari?

**Comment by mikedinicola** [comment]
Unfortunately, no dice on webm in Safari. That can't be correct about .mp4, your part 1 vid is working for me in Firefox. I'm on MacOS if that makes a difference.

**Comment by schwartzworld** [comment]
I think the real answer is probably finding a peertube instance then. 🙃

**Comment by schwartzworld** [comment]
> Unfortunately, no dice on webm in Safari. That can't be correct about .mp4, your part 1 vid is working for me in Firefox. I'm on MacOS if that makes a difference.

The video should be working again. I've decided that the ability to maintain a conversation across multiple posts is a feature and not a bug.

**Comment by mikedinicola** [comment]
Sure, no issue having comments shared as long as it's intentional.

I'm able to see the video in Chrome, which I actually don't think I tried before because I hate Chrome. But it's still broken in Firefox (and Safari as expected). FF says "No video with supported format and MIME type found"
